version: '3'
services:
  server:
    image: roberniro/ossproj-server:6.0
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    networks:
      - lms-demo-net
    restart: always

  view:
    image: roberniro/ossproj-view:1.0
    ports:
      - 3000:3000
    networks:
      - lms-demo-net
    restart: always

  mysql:
    image: roberniro/ossproj-mysql:1.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eclass
    networks:
      - lms-demo-net
    restart: always

  redis:
    image: roberniro/ossproj-redis:1.0
    ports:
      - 6380:6379
    networks:
      - lms-demo-net
    restart: always

networks:
  lms-demo-net:
    driver: bridge